name: Check if presubmit
on:
  pull_request:
    types: [labeled,opened,reopened,synchronize]
jobs:
  check_if_presubmit:
    runs-on: ubuntu-latest
    name:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci --prefix .github/actions/presubmit

      - name: Check if presubmit
        id: presubmit
        uses: ./.github/actions/presubmit
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          is_presubmit: ${{ contains(github.event.pull_request.labels.*.name, '$-presubmit') }}
